### PR TITLE
Fix trigger for nats-manager unit test job

### PR DESCRIPTION
**Pull request by grischperl**
**Description**
`pull-nats-manager-unit-test` was not getting triggered on nats-manager PRs. The regex pattern needed to be slightly changed to fix the trigger.

The job will now get triggered if the following files are changed:
- {any folder structure}/file.go
- go.mod
- go.sum

**Related issue(s)**

### CODE REVIEW

**Review by k15r — CHANGES_REQUESTED** [review]
Please setup codeownership for the nats-manager jobs

**Review by k15r — APPROVED** [review]

**Review by halamix2 — APPROVED** [review]
/cla-recheck

**Pull request merged**
