### PR TITLE
switch serverless-git job to trusted cluster

### PR DESCRIPTION
**Pull request by Halamix2**
**Description**

Changes proposed in this pull request:

- this job uses its own github key to access private repos
- limit the access to the credentials to just trusted cluster

**Related issue(s)**

### CODE REVIEW

**Review by dekiel — COMMENTED** [review]
Why this must run on trusted cluster?

**Comment by Halamix2** [comment]
This job uses ts own read-only github key to access private repos, this PR could limit the access to the credentials to just the trusted cluster

**Comment by dekiel** [comment]
If this github key is read only, must we secure it by placing in trusted cluster?

**Pull request closed without merging**
