### PR TITLE
Generate pjtester prowjobs for all repositories from templates config.

### PR DESCRIPTION
**Pull request by dekiel**
**Description**

Changes proposed in this pull request:

- Modify pjtester prowjob template to generate jobs for all repos defined in templates/config file.

Pjtester will support triggering tests from PRs created in all repos in kyma organisations. Prowjobs for running pjtester must be present for all repos in kyma orgs.

### CODE REVIEW

**Comment by dekiel** [comment]
@Ressetkk @tobiscr please review.

**Review by kasiakepka — APPROVED** [review]

**Comment by dekiel** [comment]
/override pre-main-test-infra-validate-generated-files
Nothing changed after running rendertemplate.

**Pull request merged**
