### PR TITLE
Fix pull-gitleaks Github action

### PR DESCRIPTION
**Pull request by Sawthis**
**Description**

Changes proposed in this pull request:

- Fix pull-gitleaks Github action by changing event from pull_request to pull_request_target

**Related issue(s)**

### CODE REVIEW

**Review by dekiel — CHANGES_REQUESTED** [review]
What we are fixing here? Why using pull request target event does fix the problem?

**Comment by Sawthis** [comment]
@dekiel https://github.com/kyma-project/test-infra/actions/runs/8293289687/job/22696095561

when you use pull_request_target then variables are passed to the pull requested created from forks, the same target is used in Pull Plan Prod Terraform

**Comment by dekiel** [comment]
> @dekiel https://github.com/kyma-project/test-infra/actions/runs/8293289687/job/22696095561
> 
> when you use pull_request_target then variables are passed to the pull requested created from forks, the same target is used in Pull Plan Prod Terraform

From the execution you shared I don't know what the problem is. Could you please elaborate more what is missing, that the action can't run?
Why passing variables is a problem?
I was aware about restrictions to access secrets for pull request event, not to acsess variables.  Could you please share a documentation about that?
If you switch to the pull request target event you need to adjust the checkout step as you are working with base branch not the code changed in pull request.

**Comment by Sawthis** [comment]
@dekiel I found this solution here: https://github.com/orgs/community/discussions/44322#discussioncomment-4914222
I will adjust checkout step

**Comment by dekiel** [comment]
@Sawthis I would not go with pull_request_target event here. In my opinion we should think about other solution than just using pull_request_target. Using this event has security related consequences as well require to pay attention to the code version you are working with.

The discussion you shared contains some ideas and links to alternative solution. Maybe we can use some of it for this kind of workflow executions? For now we have at least two and I'm sure will be more.

Interesting that official documentation says nothing about this restriction.

**Comment by dekiel** [comment]
@Sawthis This alternative solution looks promising. What do you think?

https://github.com/orgs/community/discussions/44322#discussioncomment-7212990
https://github.com/orgs/community/discussions/44322#discussioncomment-7219285

**Comment by Sawthis** [comment]
@dekiel I would not store variables like google project id in the repository file. 

[Official documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) says that "Avoid using this event if you need to build or run code from the pull request.". We don't build or run code in this workflow so I think it is safe to use pull_request_target event.

In the future when we will need to build or run code from pull requests created from forks I would use solution described [here](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) based on workflow_run event.

**Comment by dekiel** [comment]
@Sawthis we already store this id in the repo https://github.com/kyma-project/test-infra/blob/0bbc923177165e2929b243295e71ded606a88a91/configs/terraform/environments/prod/variables.tf#L13

It's not only about build or run code from pull request. By using `pull_request_target` event you give a gitleaks rights to ready any secret in github org. moreover a github token mounted for the workflow has full rights in repo or org as well. It would be nice to not give the tool so much rights if it does not need it. Especially that you don't need to expose anything new to the public Internet when using a config file in repo.

**Comment by Sawthis** [comment]
@dekiel I don't understand then why this approach was used for terraform/tofu workflows when it is so unsecure?

**Comment by dekiel** [comment]
@Sawthis that's a good question. Maybe they should be changed too.

**Comment by Sawthis** [comment]
New pull request will be created by @KacperMalachowski .

**Pull request closed without merging**
