### PR TITLE
Create a Prow Job for Istio Injection Integration Tests

### PR DESCRIPTION
**Pull request by muralov**
**Description**
This PR is about to create a Prow Job for Istion Injection Tests.

Changes proposed in this pull request:

- Create a Prow Job for istion injection integration tests

Issue: #2447

### CODE REVIEW

**Comment by muralov** [comment]
@colunira @piotrmsc do you know why some checks are failing? Should I sync my fork with upstream? The errors seem to be not related to my changes.

**Comment by colunira** [comment]
@muralov I'm investigating it, looks like some infrastructure error

**Comment by piotrmsc** [comment]
@muralov can you resolve conflicts?

**Comment by muralov** [comment]
> @muralov can you resolve conflicts?

@piotrmsc yes, I can resolve conflicts, but I am afraid I cannot do another refactoring @jakkab asked me. I don't have much time due to load at work. However, if Jakub commented earlier, I could do it. It is now really late from my side.

**Pull request closed without merging**
