### PR TITLE
Components Cleanup

### PR DESCRIPTION
**Pull request by ralikio**
**Description**

Changes proposed in this pull request:

- Removal of deprecated components of `service-catalog` and `helm-broker`.

**Related issue(s)**

### CODE REVIEW

**Review by tillknuesting — APPROVED** [review]

**Comment by tillknuesting** [comment]
go run development/tools/cmd/rendertemplates/main.go --config templates/config.yaml --templates templates/templates --data templates/data
    in the root directory of the test-infra repository and commit changes.

**Review by dekiel — CHANGES_REQUESTED** [review]
Please fix failed tests.

**Comment by ralikio** [comment]
Not relevant anymore.

**Review by tillknuesting — APPROVED** [review]

**Review by dekiel — APPROVED** [review]

**Pull request merged**
