### PR TITLE
Restore jobs for testing compass-runtime-agent

### PR DESCRIPTION
**Pull request by koala7659**
Restoring following jobs to execute component tests for `compass-runtime-agent`:

- pre-main-kyma-integration-k3d-runtime-agent
- post-main-kyma-integration-k3d-runtime-agent

### CODE REVIEW

**Comment by franpog859** [comment]
I set up the `preset-kyma-integration-compass-dev: "true"` preset for the `*-main-kyma-integration-k3d-runtime-agent` jobs. It sets up four environment variables in the pipeline so they could be used while running the makefile commands. These variables are `COMPASS_TENANT`, `COMPASS_HOST`, `COMPASS_CLIENT_ID` and `COMPASS_CLIENT_SECRET`

According to the internal documentation, we need Director GraphQL API URL, Token endpoint URL, ClientID for obtaining the token, and ClientSecret to be configured. Using the `COMPASS_HOST` environment variable, the Director GraphQL API URL could be built as `https://compass-gateway-auth-oauth.${COMPASS_HOST}/director/graphql`, and the Token endpoint URL could be built as `https://oauth2.${COMPASS_HOST}/oauth2/token`. The ClientID and the ClientSecret could be used directly from `COMPASS_CLIENT_ID` and `COMPASS_CLIENT_SECRET` variables

**Comment by akgalwas** [comment]
/test 
pre-main-test-infra-validate-generated-files

**Comment by Halamix2** [comment]
Could you regenerate prowjobs?

**Review by Halamix2 — APPROVED** [review]

**Review by majakurcius — APPROVED** [review]

**Review by grego952 — APPROVED** [review]

**Pull request merged**
