### PR TITLE
Add telemetry-manager integration test

### PR DESCRIPTION
**Pull request by chrkl**
**Description**

Changes proposed in this pull request:

- Add telemetry-manager integration test

**Related issue(s)**

https://github.com/kyma-project/kyma/issues/16909

### CODE REVIEW

**Comment by chrkl** [comment]
Tested successfully: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_telemetry-manager/44/chrkl_test_of_prowjob_pull-telemetry-manager-integration-test/1631583653735698432

**Review by hisarbalik — APPROVED** [review]

**Comment by chrkl** [comment]
Successfully tested https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_telemetry-manager/55/chrkl_test_of_prowjob_pull-telemetry-manager-integration-test/1631685028641509376

**Review by skhalash — APPROVED** [review]

**Comment by skhalash** [comment]
Btw, the Ginkgo CLI output looks nice 👍🏻

**Review by Sawthis — APPROVED** [review]

**Pull request merged**
