### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by kasiakepka**
**Description**

Changes proposed in this pull request:

- add @kyma-bot as an owner
- delete rules for paths that no longer exist

**Related issue(s)**

### CODE REVIEW

**Review by dekiel — COMMENTED** [review]
Is this about letting automated approvals of automated versions/dependencies updates? The solution proposed by Piotr on our retro?

**Comment by kasiakepka** [comment]
Yes, exactly.

**Review by dekiel — CHANGES_REQUESTED** [review]
For this use case an owner should be neighbors-dev-bot instead. Our approval automation is using this identity. Moreover some dependency/version update PRs are created by kyma-bot. Because of GitHub settings, kyma-bot can't approve it's owne PRs.

**Review by dekiel — APPROVED** [review]

**Pull request merged**
