### PR TITLE
ProwJobs for triaging stale issues as central configuration

### LINKED ISSUE #5707: Unstale issues or PRs when activity happen on issue or PR.
**Description**
Stale bot should unstale issue or PR when any activity happen on it. At present all stale issues require manual removal of stale label.

Example comment on issue which didn't unstale it. https://github.com/kyma-project/kyma/issues/14147#issuecomment-1174482327

Stale bot documentation: https://github.com/kyma-project/community/pull/689/files#commit-suggestions

Example unstale by any comment: https://github.com/fluent/fluent-bit/issues/2752#issuecomment-1177044544

### LINKED ISSUE #5786: Migrate stale issues triaging to a new tooling
/kind deprecation
/area ci
/area prow

Follow-up for #5707 

Current stale-bot is not maintained for over a year by its authors. We should migrate that to something else that will give us the same functionality of current tooling.

**Acceptance criteria**:

- [ ] Configuration is centralized for all repos across all prow-enabled orgs
- [ ] Bot gives comprehensive comment about it's workings
- [ ] Automatically un-stales issue when there is activity, or gives instruction on how to un-stale the issue/PR
- [ ] Works on both PRs and issues
- [ ] Must run on Prow

### PR DESCRIPTION
**Pull request by Ressetkk**
Closes #5786 

This approach handles triaging stale issues a little bit differently:
* Uses generic github commenter application to operate on lifecycle labels using the `lifecycle` Prow plugin
* When the issue is marked as stale or closed, a simple instruction is posted on how to un-stale the issue and link to where create an issue when something goes bad
* Job runs every hour and operates on centralized configuration, that is automatically used on ALL prow-enabled organisations

This approach reduces the time that is required to maintain the stalebot configuration and deprecates our own probot stale instance completely.

/kind deprecation
/hold

### CODE REVIEW

**Comment by dekiel** [comment]
So what this tool will do?
Mark issue as stale by adding some label, if issue is not active for some time. Thats it?
Removing stale label will be manual action in any case, right?

**Comment by Ressetkk** [comment]
@dekiel yep. It will mark issue as stale after 60 days of inactivity, then after 7 days of inactivity it will close the issue.
* It will not be able to automatically remove stale issue, but we give the author the instruction on how to do it, if they wish to
* If there is activity, but the issue is stale, the tool will not close the issue, unless there is 7 days of inactivity on that Issue. Unstalling would be a manual operation based on instruction provided by the bot

It doesn't directly adds functionality of removing stale label when there's activity, but it gives more advantages of using it in centralized way. We resolve the problem by giving authors clear instructions.

Adding/removing label could consume the token too quickly, given that it has to operate on every issue/pr on repos.

**Review by dekiel — CHANGES_REQUESTED** [review]
Then this PR is not relevant for the issue you are going to close. This PR doesn't provide a feature user asked for. We planned to add a feature user asked for not replace a tool to another one. Please provide solution for user request.

**Comment by Ressetkk** [comment]
@dekiel it doesn't directly touches the issue, but it invalidates the need for such feature, because the author has simple instruction on how to remove the stale label. Having the instruction posted on every stale issue should be enough for the dev to understand how it works. This feature conveniently gives us the feature of having the triaging in central place. Without the need of adding any code, and maintaining any tools.

**Comment by dekiel** [comment]
Current tool allow us to add some instructions too. There is no need to replace the tool for that. At least now. Users wanted to have issues unstale automatically when activity happen, not have an instruction how to unstale issue. Provide requested feature or close tickets with explanation.

**Comment by Halamix2** [comment]
This tool compared to the Github Action:
* we have one central config for all repositories in organizations, less maintenance
* We have better comments with easy instruction how to unstale

**Comment by Sawthis** [comment]
I think if the current stale-bot is not maintained we should migrate to other solution. New solution has already some benefits described in [the comment](https://github.com/kyma-project/test-infra/pull/5785#issuecomment-1194020069) and we can get it with minimal effort. I think we can create follow-up issue for: https://github.com/kyma-project/test-infra/issues/5707 which is closed already anyway.

**Review by dekiel — DISMISSED** [review]

**Comment by Ressetkk** [comment]
Let's see how it will work out
/unhold

**Comment by Ressetkk** [comment]
typos fixed
/unhold

**Review by Halamix2 — APPROVED** [review]

**Pull request merged**
