### PR TITLE
Grouped secrets leak detector prowjobs.

### LINKED ISSUE #6993: Run terraform plan and apply on workflow change.
**Description**

When a gcp workflow file is changed it should trigger a terraform plan and apply execution. Terraform will plan and apply new workflow content making a running workflow reflecting a state in files.

A workflow file path: `development/gcp/workflows/secrets-leak-detector.yaml`

### PR DESCRIPTION
**Pull request by dekiel**
**Description**

Changes proposed in this pull request:

- Hiding tf comments has it's own prowjob file with more generic run if changed paths.
- Grouped prowjobs for building images and applying tf config of secret leak detector in one file.
- Running tf plan and tf apply on chagnes in google workflow definition.

Closes #6993

### CODE REVIEW

**Review by Ressetkk — COMMENTED** [review]
Why do we add this many ProwJobs lately? Can it be somehow consolidated like in some kind of embedded script? This will generate unnecessary statuses on GitHub. This will be problematic during eventual clean-up.

Was this task refined? Is there some kind of written proposal on that? I kind of lost track of changes around this IaC topic.

**Comment by dekiel** [comment]
> Why do we add this many ProwJobs lately? Can it be somehow consolidated like in some kind of embedded script? This will generate unnecessary statuses on GitHub. This will be problematic during eventual clean-up.
> 
> Was this task refined? Is there some kind of written proposal on that? I kind of lost track of changes around this IaC topic.

Yes it was refined and planed. There is no written proposal. The solution was presented on at least two meetings. I'm not adding any prowjob here. Just moving, in to separate files and grouping together.

**Comment by Ressetkk** [comment]
But IIRC there was not any architectural design that I could follow to validate If it meets the given requirements. 

@kasiakepka  maybe we should consider a separate directory `proposals` under `docs` or similar place, so we can keep track on anything we want to propose? Or create new issue template `enhancement proposal`, which one can use to describe given proposal which then could come down to refinement?

It's very tough for me to keep track with statuses of some features and their requirements.

**Comment by dekiel** [comment]
The proposal was presented and discussed on a meeting. If you don't understand something just ask for explanation. If you have idea about something, just share it. If you would like to discuss that please plan a meeting or raise an issue. This PR is not a place to talk about your problems in understanding the solution.

**Comment by dekiel** [comment]
A file prow/jobs/test-infra/hide-terraform-comments.yaml contains only one prowjob which is triggered on any change in files related to terraform. One common prowjob in separate dedicated file.
A file prow/jobs/test-infra/secret-leaks-log-scanner.yaml get prowjobs running terraform command on changes in terraform config files of secret leaks scanner. All prowjobs for this application in one file.

All those prowjobs were existing before in other locations. I don't see anything to consolidate here more. Please provide some concrete proposals or comments related to the changes introduced in this PR.

**Review by Ressetkk — APPROVED** [review]

**Pull request merged**
