### PR TITLE
Add job to build monitoring-custom-metrics example image

### PR DESCRIPTION
**Pull request by chrkl**
**Description**

Changes proposed in this pull request:

- Add job to build monitoring-custom-metrics example image

**Related issue(s)**

https://github.com/kyma-project/telemetry-manager/issues/317

### CODE REVIEW

**Comment by chrkl** [comment]
Current issue of the PR: The pjTest job uses the root level Dockerfile, but not the one in prometheus/monitoring-custom-metrics. See https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_examples/265/chrkl_test_of_prowjob_pull-monitoring-custom-metrics-example-bu/1697239218264215552

**Review by halamix2 — APPROVED** [review]

**Pull request merged**
