### PR TITLE
Revert "Revert "Revert "revert the switch of 3party-images to ado (#1…

### PR DESCRIPTION
**Pull request by Sawthis**
…0540)" (#10787)" (#10949)"

This reverts commit 261e39cf225e330d6aae49b9fa510bba0f53a4a4.

**Description**

Changes proposed in this pull request:

- https://github.com/kyma-project/test-infra/issues/10413

**Related issue(s)**

### CODE REVIEW

**Review by a-thaler — APPROVED** [review]

**Comment by pPrecel** [comment]
Nice revert revert revert of the revert :)

**Pull request merged**
