### PR TITLE
Name and dockerfile as required inputs.

### PR DESCRIPTION
**Pull request by dekiel**
**Description**

Changes proposed in this pull request:

Name and dockerfile path of image to build must be provided in a call to image-builder.
These inputs must not be optional.
Using some default values for these parameters doesn't make sense. User must specify which image is build.

### CODE REVIEW

**Review by Sawthis — APPROVED** [review]

**Comment by dekiel** [comment]
I will notify teams we plan this breaking change. I will give them two weeks to review their workflows and adjust to the change. For that time moving PR to blocked/waiting.

**Comment by k15r** [comment]
why not use some different defaults instead of requiring the name and Dockerfile-name?
if you use docker on your terminal all you have to specify is the PATH. so `docker build .` is a valid way to build your image. I agree the resulting image name:tag is barely usable, but the name could be by default derived from the repository.
Building from the root of the repository and using a file called `Dockerfile` would not be to unreasonable.

**Comment by dekiel** [comment]
@k15r such defaults sounds good.
image name: repository name
dockerfile path: ./Dockerfile

**Comment by KacperMalachowski** [comment]
I need to verify if it will work for every event supported by image-builder.

**Comment by KacperMalachowski** [comment]
Looks good, for details you can check: https://docs.github.com/en/webhooks/webhook-events-and-payloads

**Review by Sawthis — CHANGES_REQUESTED** [review]
Looks good to me.

We should wait with merge of this PR until 20th of November as was communicated on Kyma PO meeting.

**Review by Sawthis — APPROVED** [review]

**Pull request merged**
