### PR TITLE
Bump milv and rename kyma governance

### PR DESCRIPTION
**Pull request by dbadura**
**Description**

Changes proposed in this pull request:

- Bump milv

**Related issue(s)**

### CODE REVIEW

**Comment by dbadura** [comment]
Here is proof that milv bump works:
https://status.build.kyma-project.io/?job=dbadura*

dbadura_test_of_prowjob_kyma-governance - failed because pjtester took old version of kyma master

**Comment by dbadura** [comment]
Here is proof that milv bump works:
https://status.build.kyma-project.io/?job=dbadura*

**Review by tgorgol — APPROVED** [review]

**Pull request merged**
