### PR TITLE
Parallelise busola tests

### PR DESCRIPTION
**Pull request by dariadomagala**
**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

Resolves https://github.com/kyma-project/busola/issues/912 (part 2)

### CODE REVIEW

**Review by qbalukom — APPROVED** [review]

**Comment by Ressetkk** [comment]
Can it be done the other way? We would rather aim to *reduce* the number of ProwJobs than increase them.

**Comment by Ressetkk** [comment]
Please find your time in the future to optimise Busola pipelines without increasing the need for additional resources.

/approve

**Pull request merged**
