### PR TITLE
Updated tekton how to with details about clone-refs task.

### PR DESCRIPTION
**Pull request by dekiel**
Added information about bug.

**Description**

Changes proposed in this pull request:

- Updated tekton how to with details about clone-refs task.
- Updated tekton how to with new bug details.

See #6798

### CODE REVIEW

**Comment by dekiel** [comment]
Waiting on #7258 to merge first.

**Review by Ressetkk — COMMENTED** [review]
I see in the diff that you split some of the sentences into separate lines. Is that intended? I would avoid splitting the single sentence into multiple lines.

**Comment by dekiel** [comment]
> I see in the diff that you split some of the sentences into separate lines. Is that intended? I would avoid splitting the single sentence into multiple lines.

That's not intended. Will check that.

**Comment by dekiel** [comment]
Fixed line breaks.

**Comment by dekiel** [comment]
@IwonaLanger please review this one too. A failing governance test will be retested once #7258 will be merged. #7258 provides a resources to which  documentation in this PR links to.

**Review by IwonaLanger — APPROVED** [review]

**Pull request merged**
