### PR TITLE
Added troubleshooting logs to eventing prow jobs

### PR DESCRIPTION
**Pull request by mfaizanse**
**Description**

Changes proposed in this pull request:

- Added some troubleshooting logs, incase eventing prow jobs fail.

- Sample run with troubleshooting logs:
   - [pre-main-kyma-gardener-gcp-eventing](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/16771/mfaizanse_test_of_prowjob_pre-main-kyma-gardener-gcp-eventing/1625866718934994944)

- Sample Runs:
   - [pre-main-kyma-gardener-gcp-eventing](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/16771/mfaizanse_test_of_prowjob_pre-main-kyma-gardener-gcp-eventing/1625875583479058432)
   - [pre-main-kyma-gardener-gcp-subscription-upgrade](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/16771/mfaizanse_test_of_prowjob_pre-main-kyma-gardener-gcp-subscripti/1625875619130642432)
   - [pre-main-kyma-gardener-gcp-eventing-upgrade](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/16771/mfaizanse_test_of_prowjob_pre-main-kyma-gardener-gcp-eventing-u/1625875601338404864)

**Related issue(s)**

### CODE REVIEW

**Comment by friedrichwilken** [comment]
oh, wait, the vapth-thingy is this temporary test entity we only remove in the final step, right?

**Review by friedrichwilken — APPROVED** [review]

**Review by friedrichwilken — APPROVED** [review]

**Review by halamix2 — APPROVED** [review]

**Pull request merged**
