### PR TITLE
Extend Central Application Gateway fast integration tests to Central Application Connectivity

### PR DESCRIPTION
**Pull request by rafalpotempa**
**Description**

Changes proposed in this pull request:

- `pre-main-kyma-integration-k3s-central-app-gateway` and `...-compass` are renamed to `pre-main-kyma-integration-k3s-central-app-connectivity` and `...-compass`

**Related issue(s)**

https://github.com/kyma-project/kyma/issues/11654
https://github.com/kyma-project/kyma/pull/11676

### CODE REVIEW

**Review by franpog859 — COMMENTED** [review]
I think we can change this jobs to `required`

**Review by majakurcius — DISMISSED** [review]

**Review by franpog859 — APPROVED** [review]

**Review by majakurcius — APPROVED** [review]

**Review by Ressetkk — APPROVED** [review]

**Pull request merged**
