### PR TITLE
Go.mod: add testing

### PR DESCRIPTION
**Pull request by Halamix2**
**Description**

Changes proposed in this pull request:

- Run tools tests when `go.mod`/`go.sum` is changed
- Build prow-tools image on `go.mod`/`go.sum` change

**Related issue(s)**

#4573

### CODE REVIEW

**Review by dekiel — CHANGES_REQUESTED** [review]
We should test following tools as well:
- test-log-collector
- prowjobparser
- jobguard
- checker/unique-jobs-name

**Comment by Halamix2** [comment]
I've added `go.mod/go.sum` to `pre-main-test-log-collector`
I don't see any job for the  `prowjobparser` tool
`Jobguard` and `unique-jobs-name` are included in `pre-test-infra-prow-tools`

**Comment by dekiel** [comment]
Can we have a job which can be run to validate all tools like `prowjobparser` or maybe we could move this tool to development/tools where I think a whole directory is covered?

**Comment by Halamix2** [comment]
Job for the `prowjobparser` is in PR #4589, already with `go.mod|go.sum` files in `run_if_changed` section

**Review by dekiel — APPROVED** [review]

**Pull request merged**
