### PR TITLE
Adjust test-infra to the new location of the `serverless-bench` and the `fixtures` directories

### PR DESCRIPTION
**Pull request by pPrecel**
**Description**

Changes proposed in this pull request:

- as in the title
- 
**Related issue(s)**

- https://github.com/kyma-project/kyma/pull/13236
- https://github.com/kyma-project/third-party-images/pull/176

### CODE REVIEW

**Comment by pPrecel** [comment]
Do not merge this PR before this:
https://github.com/kyma-project/kyma/pull/13236

**Comment by Halamix2** [comment]
I can see that we have multiple `prow/jobs` files with `post-rel124-*` jobs, probably mainly generated from `generic_component` template data file.

Currently our bumper will bump all images in all files except the ones defined in `prow/autobump-config/test-infra-autobump-config.yaml`:
```
  - "prow/jobs/kyma/releases/kyma-release-122.yaml"
  - "prow/jobs/kyma/releases/kyma-release-123.yaml"
  - "prow/jobs/kyma/releases/kyma-release-124.yaml"
 ```

**Comment by Ressetkk** [comment]
@Halamix2 can you make an issue regarding the release jobs in the generic-build template?

hold until https://github.com/kyma-project/kyma/pull/13236 gets merged
/hold

**Comment by Halamix2** [comment]
- Sure: https://github.com/kyma-project/test-infra/issues/4876

**Review by dbadura — APPROVED** [review]

**Pull request merged**
