### PR TITLE
feat: re-implement kyma2 upgrade pipelines

### PR DESCRIPTION
**Pull request by adityabhatia**
**Description**

Changes proposed in this pull request:

- Previous gardener kyma to kyma2 upgrade pipeline is removed
- New pipeline introduced to test minor version upgrades on kyma2
- Previous no. of minor versions to be tested can be specified using env variable PREVIOUS_MINOR_VERSION_COUNT

**Related issue(s)**

Partially solves: [Implement Pipelines: Scenario Kyma 2.1.x to 2.2.x](https://github.com/kyma-project/test-infra/issues/5167)

### CODE REVIEW

**Review by jakobmoellersap — APPROVED** [review]

**Comment by adityabhatia** [comment]
assign @klaudiagrz

**Review by klaudiagrz — APPROVED** [review]

**Pull request merged**
