### PR TITLE
Fix cra tests

### PR DESCRIPTION
**Pull request by VOID404**
**Description**

There was a problem with envtest setup in compass runtime agents tests.

Changes proposed in this pull request:

- call the makefile, instead of inline script in yaml

**Related issue(s)**

https://github.com/kyma-project/kyma/pull/18240

/area tests
/area application-connector
/kind failing-test

### CODE REVIEW

**Comment by VOID404** [comment]
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/void404_test_of_prowjob_pull-compass-runtime-agent-unit-test

**Comment by VOID404** [comment]
Holding until task is added in `Makefile`
/hold

**Review by koala7659 — DISMISSED** [review]
LGTM

**Review by Ressetkk — COMMENTED** [review]
I suggest using `make -C [directory] stage` instead of cd'ing into it

**Comment by VOID404** [comment]
[pj-tester log](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/18240/void404_test_of_prowjob_pull-compass-runtime-agent-unit-test/1707038110283468800)

**Review by koala7659 — APPROVED** [review]
LGTM

**Review by dekiel — APPROVED** [review]

**Pull request merged**
