### PR TITLE
Remove success alerts for k8s-prow-periodics

### PR DESCRIPTION
**Pull request by Sawthis**
**Description**

Changes proposed in this pull request:

- Remove success alerts for k8s-prow-periodics to the team kyma-neighbors-alerts Slack channel

**Related issue(s)**

/area ci
/kind chore

### CODE REVIEW

**Comment by Ressetkk** [comment]
there was a reason I've added it - to make sure daily task always finishes, and we get a notification about it. What the sudden change?

**Comment by Sawthis** [comment]
@Ressetkk if the task won't finish then we should receive notification about failure or error. What is the value from daily notification about the success? Usually we want to be notified with alert when something is wrong and we need to take some action.

**Comment by Ressetkk** [comment]
If it doesn't start at all, you may not get a notification. And with this, you know that everything is fine by simply looking at the channel

**Comment by Sawthis** [comment]
When it will not start then I think we have bigger issue with infrastructure and we should be notified by GCP about it. I am quite sure that nobody will notice missing success message on the alert channel.

**Review by Ressetkk — APPROVED** [review]
Well if you insist... Remember to set up proper alerting on infra components soon.

**Pull request merged**
