### PR TITLE
Fix compass ord-service unit tests job

### PR DESCRIPTION
**Pull request by PetarTodorovv**
**Description**
Introduce compass ord-service unit tests job

Changes proposed in this pull request:
- Add new job config running unit tests in the ord-service

**Related issue(s)**

### CODE REVIEW

**Review by la4ezar — APPROVED** [review]

**Review by dekiel — APPROVED** [review]
A failing test will be fixed in https://github.com/kyma-project/test-infra/pull/6693

**Review by dragobt — APPROVED** [review]

**Review by dekiel — APPROVED** [review]

**Review by dragobt — APPROVED** [review]

**Pull request merged**
