### PR TITLE
Analyze multiple benchmark tests in Cоmpass

### PR DESCRIPTION
**Pull request by desislavaa**
**Description**

Currently, if any benchmark test fails, the results of the next ones won't be printed

Changes proposed in this pull request:

- Add "failed" flag in order to show all benchmark results instead of exiting on the first error

### CODE REVIEW

**Comment by dekiel** [comment]
@desislavaa could you please convert this PR to draft till you will be read for review?

**Review by DimitarPetrov — APPROVED** [review]

**Review by DimitarPetrov — APPROVED** [review]

**Pull request merged**
