### PR TITLE
Do not allow for privilege escalation

### PR DESCRIPTION
**Pull request by halamix2**
**Description**

Changes proposed in this pull request:

- Set `allowPrivilegeEscalation: false` for unprivileged jobs (privileged ones requires `true`)
- exclude prow containers from checks
- fix seccomp indentation for Whitesource jobs
- fix typo in privileged constraint namespace

**Related issue(s)**

/kind chore
/area security

### CODE REVIEW

**Review by dekiel — APPROVED** [review]

**Review by k15r — APPROVED** [review]

**Review by ruanxin — APPROVED** [review]

**Review by strekm — APPROVED** [review]
/meow

**Pull request merged**
