### PR TITLE
Notify Jellyfish slack channel in case of failures

### PR DESCRIPTION
**Pull request by suleymanakbas91**
**Description**

Changes proposed in this pull request:

- Notify Jellyfish slack channel in case of failures

**Related issue(s)**

See https://github.com/kyma-incubator/reconciler/issues/593

### CODE REVIEW

**Review by dekiel — COMMENTED** [review]
What's the purpose of moving k8s test-infra extra refs?
Jobs where only one channel is set under reporter_config section will not report to ci-force. Is that you want?

**Comment by suleymanakbas91** [comment]
It's just to keep the extra-ref variables together.
Yes, we will keep an eye on our jobs ourselves instead of being ignored in the ci-force channel.

**Review by Ressetkk — APPROVED** [review]
It's a good thing that you want to keep an eye on your own jobs and I like it :)
For now the k8s test-infra dependency is required because of the reconciler autobump. Keeping them together is always a minor improvement.

/lgtm
/hold

**Pull request merged**
