### PR TITLE
Cleanup of Service Catalog code

### PR DESCRIPTION
**Pull request by wozniakjan**
**Description**

Service Catalog has been deprecated for some time and is getting fully removed in https://github.com/kyma-project/kyma/pull/13675 from kyma. Same applies for helm broker.

**Related issue(s)**

https://github.com/kyma-project/kyma/pull/13675

### CODE REVIEW

**Comment by wozniakjan** [comment]
/hold
need to wait for kyma 2.4 merge window

**Comment by tillknuesting** [comment]
I think looks fine.
/lgtm

**Comment by wozniakjan** [comment]
/unhold
got green light to merge this because SVCAT migration is finished and merge window for kyma 2.4 open

**Review by PK85 — APPROVED** [review]

**Review by Halamix2 — APPROVED** [review]

**Pull request merged**
