### PR TITLE
Remove subscription-cleanup-job

### PR DESCRIPTION
**Pull request by akgalwas**
**Description**

Changes proposed in this pull request:

- Removed Subscription Cleanup Job (the logic will be moved to KEB)

**Related issue(s)**
https://github.com/kyma-project/control-plane/issues/253

### CODE REVIEW

**Comment by Halamix2** [comment]
- Looks like this PR should be merged after https://github.com/kyma-project/control-plane/pull/1474
 /hold

**Review by Ressetkk — APPROVED** [review]

**Pull request merged**
