### PR TITLE
Modularization Operator Test Pipelines

### PR DESCRIPTION
**Pull request by jakobmoellersap**
**Description**

Changes proposed in this pull request:

- Introduce Test Pipelines for Kyma Operator (controller tests)
- Introduce Test Pipelines for Manifest Operator (api tests and controller tests)
- Introduce Test Pipelines for Kyma Watcher (operator tests and listener tests)

Creates the following Pipelines:
Kyma Operator
  - pjName: "pre-main-kyma-operator-tests" // Kyma Operator Controller+API Tests
  - pjName: "periodic-kyma-operator-tests" // Kyma Operator Controller+API Tests
  - pjName: "pre-main-kyma-operator-lint" // Kyma Operator Controller+API Lint
  
Manifest Operator
  - pjName: "pre-main-manifest-operator-controller-tests" // Manifest Operator Controller Tests
  - pjName: "periodic-manifest-operator-controller-tests" // Manifest Operator Controller Tests
  - pjName: "pre-main-manifest-operator-controller-lint" // Manifest Operator Controller Lint
  
Kyma Watcher
  - pjName: "pre-main-kyma-watcher-kcp-tests" // Kyma Watcher Operator Tests
  - pjName: "periodic-kyma-watcher-kcp-tests" // Kyma Watcher Operator Tests
  - pjName: "pre-main-kyma-watcher-kcp-lint" // Kyma Watcher Operator Lint
  - pjName: "pre-main-kyma-watcher-skr-tests" // Kyma Watcher Listener Tests
  - pjName: "periodic-kyma-watcher-skr-tests" // Kyma Watcher Listener Tests
  - pjName: "pre-main-kyma-watcher-skr-lint" // Kyma Watcher Listener Lint

**Related issue(s)**

- closes https://github.com/kyma-project/manifest-operator/issues/38
- closes https://github.com/kyma-project/kyma-operator/issues/49
- closes https://github.com/kyma-project/kyma-watcher/issues/13

### CODE REVIEW

**Review by adityabhatia — APPROVED** [review]
lgtm 🚀

**Comment by adityabhatia** [comment]
FYI: the new format for kyma-watcher is now merged with [PR](https://github.com/kyma-project/kyma-watcher)

**Review by adityabhatia — APPROVED** [review]

**Review by Halamix2 — APPROVED** [review]

**Pull request merged**
