### PR TITLE
Kyma Integration Test Image Update

### PR DESCRIPTION
**Pull request by ralikio**
**Description**

Changes proposed in this pull request:

- Update image version of skr-aws-upgrade-integration-dev tests and others.

**Related issue(s)**

### CODE REVIEW

**Review by k15r — APPROVED** [review]

**Review by triffer — APPROVED** [review]

**Review by halamix2 — APPROVED** [review]
basically a duplicate of https://github.com/kyma-project/test-infra/pull/7338

**Comment by ralikio** [comment]
Duplicate of https://github.com/kyma-project/test-infra/pull/7338

**Pull request closed without merging**
