### PR TITLE
Test eventing upgrade job with prod profile

### PR DESCRIPTION
**Pull request by VladislavPaskar**
**Description**

Changes proposed in this pull request:

- use prod profile to test NATS JetStream in clustering mode
- use better machine to test the Kyma eventing with prod profile
- check the green runs [here](https://status.build.kyma-project.io/?job=vladislavpaskar_test_of_prowjob_pre-main-kyma-gardener-gcp-even)

### CODE REVIEW

**Review by halamix2 — APPROVED** [review]

**Comment by halamix2** [comment]
`make jobs-definitions`

**Comment by VladislavPaskar** [comment]
> `make jobs-definitions`

I executed it already.

**Comment by halamix2** [comment]
Could you rebase/merge with the main branch?

**Comment by VladislavPaskar** [comment]
I just re-triggered the pipeline and it became green.

**Comment by halamix2** [comment]
LGTM, you'll need one more approval

**Review by raypinto — APPROVED** [review]
LGTM

**Review by jakobmoellersap — COMMENTED** [review]
QQ: why is it not possible to continue testing on evaluation? Probably missing the context here, other than that LGTM

**Comment by VladislavPaskar** [comment]
> QQ: why is it not possible to continue testing on evaluation? Probably missing the context here, other than that LGTM

@jakobmoellersap the reason is, that in the production profile NATS JetStream Backend is deployed in clustering mode, in the evaluation - not. The main reason of that, is that we already oversaw some changes which were green on eval and red on production due to disabled clustering.

**Review by jakobmoellersap — APPROVED** [review]

**Pull request merged**
