### PR TITLE
Add keda-manager whitesource periodic job

### PR DESCRIPTION
**Pull request by m00g3n**
**Description**

Changes proposed in this pull request:

- Add keda-manager whitesource periodic job

**Related issue(s)**

See also: https://github.com/kyma-project/keda-manager/issues/10

### CODE REVIEW

**Comment by Ressetkk** [comment]
@m00g3n please use /hold so the PR can get properly blocked.
/hold

**Review by dekiel — APPROVED** [review]

**Comment by dekiel** [comment]
@m00g3n is this PR still valid? If not please close it. If it's valid you can clear failed statuses by pushing empty commit `git commit –allow-empty -m “[EMPTY] Your commit message here”`.

**Comment by m00g3n** [comment]
the topic was postponed, lets close it for now

**Pull request closed without merging**
