### PR TITLE
Remove stability-checker

### PR DESCRIPTION
**Pull request by Ressetkk**
We don't use stability-checker anymore. We were using it along with octopus tests for kyma 1.x, and right now this functionality has been replaced by fast-integration tests on nightly. I think it's time for it to go.

/area ci
/kind cleanup

### CODE REVIEW

**Review by dekiel — CHANGES_REQUESTED** [review]
Please resolve conflicts and fix failed tests.

**Comment by Ressetkk** [comment]
@dekiel can't fix test that is about to be remove in this PR. Manual `/override pre-main-stability-checker` will be required

**Review by dekiel — APPROVED** [review]

**Review by IwonaLanger — COMMENTED** [review]
Everything looks fine to me.

**Review by IwonaLanger — APPROVED** [review]

**Review by IwonaLanger — APPROVED** [review]

**Pull request merged**
