### PR TITLE
Enable automerge for ci-prow-autobump-jobs job.

### PR DESCRIPTION
**Pull request by Ressetkk**
The autobump job creates a label that instructs tide to skip the review process and merge the opened PR by it without manual inference.

### CODE REVIEW

**Review by ammarlakis — DISMISSED** [review]

**Comment by Ressetkk** [comment]
What do we do about that PR?
/cc @dekiel

**Comment by dekiel** [comment]
@Ressetkk as agreed earlier. When notification will be in place we can enable that feature. We should enable it for all repositories where write access is revoked.

**Pull request merged**
