### PR TITLE
Remove kyma-gke-nightly-fast-integration failing job

### PR DESCRIPTION
**Pull request by pbochynski**
**Description**

Changes proposed in this pull request:

- remove periodic job [kyma-gke-nightly-fast-integration](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-gke-nightly-fast-integration) that is not watched, last successful run was on 3rd October 2022.

### CODE REVIEW

**Review by dekiel — DISMISSED** [review]

**Comment by pbochynski** [comment]
@dekiel Do you think it requires review from TWs?

**Comment by dekiel** [comment]
No this file doesn't require review from TWS. In fact this file doesn't require review at all.

**Comment by pbochynski** [comment]
Ok. Then let's wait for the review from code owners.

**Comment by Halamix2** [comment]
There's a merge confict

**Comment by pbochynski** [comment]
Because of the lengthy review process, I got merge conflicts. I rebased and pushed again. Now we start the journey again. Let's see how long will that take. If this PR would be [Apollo 11](https://en.wikipedia.org/wiki/Apollo_11) then it would be almost on the Moon (Armstrong and the crew needed 4 days to land there, we've spent already 3 days to merge this dummy PR and we still do not know who is the commander).

**Review by grego952 — APPROVED** [review]

**Review by dekiel — APPROVED** [review]

**Comment by pbochynski** [comment]
@dekiel thanks for approval but it is not required. Anyone who can write markdown files that will be approved can remove all prow jobs 🤣

**Pull request merged**
