### PR TITLE
Temporarily make app-connectivity compass job optional

### PR DESCRIPTION
**Pull request by Halamix2**
**Description**

Changes proposed in this pull request:

- Temporarily make app-connectivity compass job optional until fast-integration tests are fixed

**Related issue(s)**

- https://github.com/kyma-project/kyma/issues/13415

### CODE REVIEW

**Review by Sawthis — APPROVED** [review]

**Comment by tillknuesting** [comment]
the reason that the test was made optional was fixed here https://github.com/kyma-project/kyma/pull/14071

**Pull request merged**
