### PR TITLE
Use proper CLI version for Kyma 1.24

### PR DESCRIPTION
**Pull request by Halamix2**
**Description**

Changes proposed in this pull request:

- use CLI 1.24.8 which have `kyma test` command

**Related issue(s)**

### CODE REVIEW

**Comment by Ressetkk** [comment]
We need person with write access for now to merge to this branch.

/cc @dekiel

**Review by dekiel — APPROVED** [review]

**Comment by Halamix2** [comment]
@dekiel , can you add `approved` label by hand?

**Pull request merged**
