### PR TITLE
Use prod image builder

### PR DESCRIPTION
**Pull request by dekiel**
**Description**

image-builder image which was used in prowjobs was build manually and maintained in neighbors dev registry.
Since image-builder is build with CI system and pushed to the prod registry it should be used in all prowjobs.

Changes proposed in this pull request:

- Use image-builder image build in CI.

### CODE REVIEW

**Review by Sawthis — APPROVED** [review]

**Review by Disper — DISMISSED** [review]

**Review by Sawthis — CHANGES_REQUESTED** [review]
Please also update image URL in the https://github.com/kyma-project/test-infra/blob/main/prow/cluster/resources/gatekeeper-constraints/workloads/saKymaPushImagesSecretTrustedUsage.yaml#L19

**Comment by dekiel** [comment]
> Please also update image URL in the https://github.com/kyma-project/test-infra/blob/main/prow/cluster/resources/gatekeeper-constraints/workloads/saKymaPushImagesSecretTrustedUsage.yaml#L19

It's present in line 24 and 29.

**Pull request closed without merging**
