### PR TITLE
Remove the usage of deleted sa-gcr-push-kyma-project secret/SA in com…

### PR DESCRIPTION
**Pull request by PetarTodorovv**
**Description**
It seems with https://github.com/kyma-project/test-infra/pull/8155 the `sa-gcr-push-kyma-project secret`/`SA` was removed but there are references/labels in the compass jobs that still use this SA.

Changes proposed in this pull request:
- Change the label/SA that is used in the affected jobs - `compass-validation-data.yaml` and `compass-smoke-test-data.yaml`

**Related issue(s)**

- https://github.com/kyma-project/test-infra/pull/8155

### CODE REVIEW

**Review by ivantenevvasilev — APPROVED** [review]

**Review by halamix2 — APPROVED** [review]

**Comment by halamix2** [comment]
- Linking to #8178

**Pull request merged**
