### PR TITLE
Support godog tests in API-gateway pipeline

### PR DESCRIPTION
**Pull request by barchw**
**Description**

Changes proposed in this pull request:

-  Adjust API-Gateway pipeline to use "make test" and show test results

**Related issue(s)**

https://github.com/kyma-project/kyma/pull/14744
https://github.com/kyma-project/kyma/issues/14473

### CODE REVIEW

**Review by dekiel — DISMISSED** [review]
Please remove pjtester from PR.

**Comment by barchw** [comment]
This PR is waiting for https://github.com/kyma-project/kyma/pull/14744. Will unhold it when that one is ready.

**Review by cnvergence — APPROVED** [review]

**Review by klaudiagrz — APPROVED** [review]

**Review by dekiel — APPROVED** [review]

**Pull request merged**
