### PR TITLE
Add image build jobs

### PR DESCRIPTION
**Pull request by chrkl**
**Description**

Changes proposed in this pull request:

- Add image build job for alertmanager
- Add image build job for configmap-reload

**Related issue(s)**

https://github.com/kyma-project/third-party-images/pull/333
https://github.com/kyma-project/third-party-images/pull/336
https://github.com/kyma-project/kyma/issues/17378

### CODE REVIEW

**Review by rakesh-garimella — APPROVED** [review]

**Comment by chrkl** [comment]
Successfully tested:
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_third-party-images/333/chrkl_test_of_prowjob_pre-main-tpi-alertmanager/1653732308336775168
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_third-party-images/336/chrkl_test_of_prowjob_pre-main-tpi-configmap-reload/

**Review by the1bit — APPROVED** [review]

**Pull request merged**
