### PR TITLE
Exclude eventing and compass tests from purely skr-test changes

### PR DESCRIPTION
**Pull request by wozniakjan**
**Description**

As part of https://github.com/kyma-project/kyma/pull/14298, the tests under `tests/fast-integration/skr-test` no longer execute eventing and compass related tests therefore changes exclusively on those files shouldn't trigger them.

### CODE REVIEW

**Review by tillknuesting — APPROVED** [review]

**Review by Ressetkk — CHANGES_REQUESTED** [review]
This change will not be propagated to the resulting files, as the template in https://github.com/kyma-project/test-infra/blob/d7e71adac2567016dc37e4c87068a92ca68d1cc6/templates/templates/generic.tmpl#L25 does not include directive `skip_if_only_changed`. Could you please add it the same way as `run_if_changed` to linked template?

**Comment by tillknuesting** [comment]
> 

@Ressetkk Can you have a look if the change is what you suggested? I am not familiar with Prow that much.

**Comment by Ressetkk** [comment]
> > 
> 
> 
> 
> @Ressetkk Can you have a look if the change is what you suggested? I am not familiar with Prow that much.

Exactly that what I meant. You need to re-run rendertemplates binary to regenerate the result files and you should be good to go.

**Comment by tillknuesting** [comment]
@Ressetkk Could you have a look? `go run github.com/kyma-project/test-infra/development/tools/cmd/rendertemplates --config templates/config.yaml --templates templates/templates --data templates/data` does not produce for me any changes?

**Comment by Ressetkk** [comment]
Keep in mind that `run_if_changed` and `skip_if_only_changed` are mutually exclusive, as per [the official docs](https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#triggering-jobs-based-on-changes).

**Comment by wozniakjan** [comment]
> Keep in mind that `run_if_changed` and `skip_if_only_changed` are mutually exclusive, as per [the official docs](https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#triggering-jobs-based-on-changes).

ah, thanks. Well given prow is using go regexp library which doesn't have negative lookahead, I guess will need to do this same way markdown files are excluded with `(\\.[^.][^.][^.]+$|\\.[^.][^dD]$|\\.[^mM][^.]$|\\.[^.]$|/[^.]+$)`

**Review by dekiel — APPROVED** [review]

**Pull request closed without merging**
