### PR TITLE
Backport kyma::get_last_release_version to release-1.24

### PR DESCRIPTION
**Pull request by Halamix2**
**Description**

Changes proposed in this pull request:

- backport function that correctly selects the latest Kyma 1.24 release

**Related issue(s)**

 #4996

### CODE REVIEW

**Review by Ressetkk — CHANGES_REQUESTED** [review]
I believe the `-v` parameter should follow the `1\.` regular expression. Why do you restrict the changes only in `1.24` version?

**Review by dekiel — APPROVED** [review]

**Comment by dekiel** [comment]
@Halamix2 I will approve again when you answer @Ressetkk comment.

**Comment by Halamix2** [comment]
I've fixed the `-v 1\.24`  flag.

**Review by Ressetkk — APPROVED** [review]

**Pull request merged**
