### PR TITLE
[WIP] test prowjobs

### PR DESCRIPTION
**Pull request by VladislavPaskar**
This PR is used only for a debugging purpose

### CODE REVIEW

**Comment by VladislavPaskar** [comment]
Was used to test this pr: https://github.com/kyma-project/kyma/pull/13485

**Comment by Ressetkk** [comment]
@VladislavPaskar if you are done please use /auto-cc command to assign reviewers again.
/uncc @Ressetkk @Halamix2

**Comment by Ressetkk** [comment]
I see no activity.
/close

**Pull request closed without merging**
