### PR TITLE
Fix kubectl version in cluster infra image

### PR DESCRIPTION
**Pull request by michal-hudy**
**Description**

Changes proposed in this pull request:

- Fixed kubectl version in cluster infra image

Job with new kubernetes that is using this image: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/5789/pre-master-kyma-gke-integration/1178615946688860160

**Related issue(s)**

### CODE REVIEW

**Comment by mszostok** [comment]
My two cents: for me, this one is more like a hot-fix. The proper fix should define where we want to define the `kubectl` version that will be used on our CI. Because in bootstrap we have
```
 gcloud components install alpha beta kubectl docker-credential-gcr
```
so deleting that here and adding once again imo could be only error-prone

**Comment by michal-hudy** [comment]
@mszostok yes, but the problem is that we will need to update all images that is using bootstrap so in fact all images used by our prow and then update that in jobs...so it makes the task really complicated if we only want to migrate to the new version of k8s cluster

**Comment by mszostok** [comment]
I know, and this is why I treat that as hot-fix. But sometimes fixing something in a propper way takes some time:)

**Comment by michal-hudy** [comment]
Fixed on master

**Pull request closed without merging**
