### PR TITLE
Istio reconcilation component test pipeline

### PR DESCRIPTION
**Pull request by barchw**
**Description**

Changes proposed in this pull request:

- Setup a pipeline for running reconciler related component tests

**Related issue(s)**

https://github.com/kyma-project/kyma/issues/15279

### CODE REVIEW

**Comment by videlov** [comment]
lgtm

**Review by videlov — APPROVED** [review]
/lgtm

**Review by cnvergence — APPROVED** [review]

**Review by Halamix2 — APPROVED** [review]

**Review by grego952 — APPROVED** [review]

**Pull request merged**
