### PR TITLE
Istio gcp integration test

### PR DESCRIPTION
**Pull request by barchw**
**Description**

Changes proposed in this pull request:

- Run Istio tests on GCP

**Related issue(s)**

- https://github.com/kyma-project/test-infra/issues/7564

### CODE REVIEW

**Comment by barchw** [comment]
Pipeline run: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_istio/163/barchw_test_of_prowjob_pull-istio-operator-integration-gcp/1665979597453266944

**Review by triffer — DISMISSED** [review]

**Review by triffer — APPROVED** [review]

**Review by halamix2 — APPROVED** [review]

**Pull request merged**
