### PR TITLE
Use kubectl directly instead of SSH

### PR DESCRIPTION
**Pull request by Halamix2**
**Description**

Changes proposed in this pull request:

- Use ssh only to provision k3d cluster on a VM
- Run kubectl/kyma commands from the job pod level
- ...

**Related issue(s)**

- #5442

### CODE REVIEW

**Comment by Halamix2** [comment]
- blocked by https://github.com/kyma-project/cli/issues/1291

**Comment by kasiakepka** [comment]
@Halamix2 do you plan to work on it? Please close it if you don't ;)

**Comment by Ressetkk** [comment]
@kasiakepka this PR is still blocked by lack of support for external registries when using K3s/K3d. We should evaluate if #5442 is still relevant.

**Comment by Halamix2** [comment]
I can close this PR, since the issue is till open, linked to the blocker and has correct labels

**Pull request closed without merging**
