### PR TITLE
Remove not used pjobs and tools.

### PR DESCRIPTION
**Pull request by dekiel**
**Description**

Changes proposed in this pull request:

- removed prowjobs
- removed whole templates dir
- removed tools used in removed pjobs
- go mod tidy to reflect changes

### CODE REVIEW

**Review by IwonaLanger — APPROVED** [review]

**Comment by Sawthis** [comment]
part of: https://github.com/kyma-project/test-infra/issues/11627

**Review by Sawthis — APPROVED** [review]

**Review by Sawthis — APPROVED** [review]

**Pull request merged**
