### PR TITLE
Improve tfcmt GitHub comments.

### PR DESCRIPTION
**Pull request by dekiel**
**Description**

Changes proposed in this pull request:

- Modified tfcmt config to not HTML escape. When a terraform plan result contains changes in k8s manifests and it was HTML escaped the result is polluted with unrelevant GitHub links and special keywords processing.
- Run hide github in one prowjob after terraform to make it compatible with tfctm patch plan option.

/kind bug
/area automation

### CODE REVIEW

**Comment by halamix2** [comment]
Will you also reword the OPA constraints?

**Comment by dekiel** [comment]
> Will you also reword the OPA constraints?

Why we need reword them and how I should change them?

**Comment by halamix2** [comment]
Both `prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSecretTrustedUsage.yaml` and `prow/cluster/resources/gatekeeper-constraints/workloads/terraformExecutorK8sSaTrustedUsage.yaml` are referencing these jobs, if you change args in them these constraints will catch that

**Comment by dekiel** [comment]
Right, forgot about that. Yes, will update OPA constraints as well.

**Review by Ressetkk — APPROVED** [review]

**Pull request merged**
