### PR TITLE
chore: prepare 2.9 update

### PR DESCRIPTION
**Pull request by Ressetkk**

### CODE REVIEW

**Review by Sawthis — APPROVED** [review]

**Review by dzahariev — APPROVED** [review]

**Comment by dzahariev** [comment]
@Ressetkk, 
look like some formatting are not aligned:
```run "goimports -w -l" against the development/tools/ and commit your changes```

**Comment by Ressetkk** [comment]
/override pre-main-test-infra-validate-prow-jobs

Job will be removed in favor of central `pull-unit-test-go`

**Review by Sawthis — APPROVED** [review]

**Pull request merged**
