### PR TITLE
Tekton PR pipeline for istio repository

### PR DESCRIPTION
**Pull request by Ressetkk**
/area ci
/kind feature

Tekton PR pipeline for istio repository. It's meant to replace all validation jobs that run on PR level in istio repo.

### CODE REVIEW

**Comment by Ressetkk** [comment]
/retitle Tekton PR pipeline for istio repository

**Review by halamix2 — APPROVED** [review]
/this-is-fine

**Comment by Ressetkk** [comment]
/assign @barchw @triffer 
Please take a look at current state

**Pull request closed without merging**
