### PR TITLE
Remove reviewers for markdown files

### PR DESCRIPTION
**Pull request by pbochynski**
**Description**

Changes proposed in this pull request:
- Remove codeowners for markdown files. Markdown files are generated by the script, no need to review them.

### CODE REVIEW

**Comment by dekiel** [comment]
@pbochynski We use .md files for documentation and they are not generated by script. Why you think all .md files are generated by script in test-infra repo?

**Comment by pbochynski** [comment]
> @pbochynski We use .md files for documentation and they are not generated by script. Why you think all .md files are generated by script in test-infra repo?

/docs folder has technical writers as codeowners
This is an example: https://github.com/kyma-project/test-infra/pull/6237
The PR contains a change in generated file [test-inventory-integration.md](https://github.com/kyma-project/test-infra/blob/main/test-inventory-integration.md) and waits for TWs review.

**Comment by dekiel** [comment]
> > @pbochynski We use .md files for documentation and they are not generated by script. Why you think all .md files are generated by script in test-infra repo?
> 
> It is removing just this strange rule at the end of the file. The actual documentation (/docs folder) has still technical writers as codeowners. This is an example: #6237 The PR contains a change in generated file [test-inventory-integration.md](https://github.com/kyma-project/test-infra/blob/main/test-inventory-integration.md) and waits for TWs review.

We have .md files not generated by scripts in other directories than /docs. I believe inventory-integration.md](https://github.com/kyma-project/test-infra/blob/main/test-inventory-integration.md) is the only one .md file generated by script at the moment.

Here are examples of PRs outside /docs folder, where .md file with documentation was changed.
https://github.com/kyma-project/test-infra/pull/4365
https://github.com/kyma-project/test-infra/pull/5726

**Comment by pbochynski** [comment]
I will not fight - you are the code owner :)

**Pull request closed without merging**
