### PR TITLE
Reorganize jobs to remove build-generic.sh usage

### PR DESCRIPTION
**Pull request by Ressetkk**
Unfortunately make targets were so cluttered I've decided to leave docker in docker.
I've extracted hydroform jobs and removed usage of build-generic.sh because this repo is on kyma-project.

Kyma-dashboard, reconciler and fast integration tests left.

### CODE REVIEW

**Comment by dekiel** [comment]
I've started reviewing this PR.
@Ressetkk Do we have agreement with @TorstenD-SAP that security is accepting exception for privileged containers required for docker in docker? Or we have another plan for that?

**Comment by Ressetkk** [comment]
From what I remember from previous discussion we are allowed to use privileged containers as long as the following requirement is met:
>containers images can only be deployed from trusted registries in combination with no high rated CVSSv3.1 scores

Once we clean up and pin security scans to test images we'll fully meet this requirement.

**Review by dekiel — CHANGES_REQUESTED** [review]
A meeting to clarify our position on privileged containers is planned for 05.04.2023.

**Pull request closed without merging**
