### PR TITLE
Make compass performance tests optional

### PR DESCRIPTION
**Pull request by DimitarPetrov**
**Description**

Compass performance tests should be optional and should not block PR merging.

**Related issue(s)**

### CODE REVIEW

**Review by NickyMateev — APPROVED** [review]

**Review by NickyMateev — APPROVED** [review]

**Review by NickyMateev — APPROVED** [review]

**Review by NickyMateev — APPROVED** [review]

**Review by NickyMateev — APPROVED** [review]

**Review by NickyMateev — CHANGES_REQUESTED** [review]
something

**Review by NickyMateev — APPROVED** [review]

**Review by dekiel — APPROVED** [review]

**Review by adamwalach — APPROVED** [review]

**Pull request merged**
