### PR TITLE
Serverless Functions Benchmarks

### PR DESCRIPTION
**Pull request by moelsayed**
**Description**

Changes proposed in this pull request:

- Define Serverless functions benchmark job
- Add benchmark run script
- Update serverless grafana dashboard.

**Related issue(s)**

### CODE REVIEW

**Review by dbadura — COMMENTED** [review]
Consider to move all those `function cr` to` kyma-project` repo and `test/serverless-bench` directory

**Review by pPrecel — APPROVED** [review]

**Review by Ressetkk — CHANGES_REQUESTED** [review]
Why do those fixtures need to be on the test-infra? Job runs against kyma-project/kyma and those files should be placed in there.

**Comment by moelsayed** [comment]
@Ressetkk We already have ticket to move the fixtures and the image to the kyma repo. But we need the data from this test ASAP. So, we will move things around in follow up PR(s).

**Comment by Ressetkk** [comment]
Approved on one condition - the files unrelated to the test-infra will be removed from the repo ASAP.
@kyma-project/technical-writers Will also need to review this PR.
/approve

**Review by mmitoraj — APPROVED** [review]

**Pull request merged**
