### PR TITLE
Fix checkout ref

### PR DESCRIPTION
**Pull request by dekiel**
**Description**

Changes proposed in this pull request:

Checkout proper pull request merge commit.
Validate the merged commit did not changed.

/kind feature
/area automation

### CODE REVIEW

**Review by KacperMalachowski — APPROVED** [review]

**Comment by dekiel** [comment]
/override Pull Plan Prod Terraform / pull-plan-prod-terraform (pull_request_target)

**Comment by dekiel** [comment]
/override "Pull Plan Prod Terraform / pull-plan-prod-terraform (pull_request_target)"

**Pull request merged**
